### ISSUE TITLE
test function second argument

### ISSUE THREAD

**Issue by AIRTucha** [pauldijou/elm-ordeal#1]
Hi, @pauldijou, Thank you for an amazing project. I just faced Task testing and it was really amazing that I found your lib.

Btw, I am wondering, why isn't second argument a function?

**Comment by pauldijou** [comment]
Glad it could help.

Which 2nd argument are you talking about?

**Comment by AIRTucha** [comment]
I am sorry for a bit messy original message.

So, you have this example:
``` Elm
test "My very first test" (  "a" |> shouldEqual "a" )
```

As fas as I understand the second argument (`"a" |> shouldEqual "a"`) is an Expectation, while usually it is () -> Expectation at elm-test.

At least testing frameworks, I used to work before (Mocha, elm-test, JUnit and so on) do it this way. But my question might be irrelevant since Elm is purely function, therefore based on Church–Rosser theorem it should not matter.

**Comment by pauldijou** [comment]
I wanted an `Expectation` to be anything handled by the test runner and not always a function. You can use `lazy` if you want a function.
